AWSTemplateFormatVersion: 2010-09-09
Description: IAM role that delegates access to another trusted AWS account.

Parameters:
  TrustedAccountId:
    Description: AWS account ID of the external trusted account.
    Type: String

Resources:
  CrossAccountAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${TrustedAccountId}:root
        Version: 2012-10-17
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - iam:AddUserToGroup
            - iam:AttachGroupPolicy
            - iam:AttachUserPolicy
            - iam:ChangePassword
            - iam:CreateAccessKey
            - iam:CreateAccountAlias
            - iam:CreateGroup
            - iam:CreateLoginProfile
            - iam:CreateUser
            - iam:DeleteAccessKey
            - iam:DeleteAccountAlias
            - iam:DeleteAccountPasswordPolicy
            - iam:DeleteGroup
            - iam:DeleteGroupPolicy
            - iam:DeleteLoginProfile
            - iam:DeleteUser
            - iam:DeleteUserPolicy
            - iam:DetachGroupPolicy
            - iam:DetachUserPolicy
            - iam:GetAccountSummary
            - iam:ListAttachedUserPolicies
            - iam:PutGroupPolicy
            - iam:PutUserPolicy
            - iam:RemoveUserFromGroup
            - iam:UpdateAccessKey
            - iam:UpdateGroup
            - iam:UpdateUser
            - organizations:*
            Effect: Deny
            Resource: "*"
          - Action: [ "*" ]
            Effect: Allow
            Resource: "*"
          Version: 2012-10-17
        PolicyName: CrossAccountAccess

Outputs:
  CrossAccountAccessRoleArn:
    Description: ARN of IAM role used for cross-account access.
    Value: !GetAtt CrossAccountAccessRole.Arn
